### ISSUE TITLE
What functionality is known to work with reclass?

### ISSUE THREAD

**Issue by rlewkowicz** [memflow/memflow-pcileech#6]
I figured out where to put the pcileech plugin (right next to the reclass executable, not the plugins folder near the memflow dll for anyone else out there). I can list processes, I can attach to processes. 

I try to run a scan and it seems to hang. I'm going to walk away for a few hours and start work see if it's done its thing by the time I get back.

**Comment by ko1N** [comment]
This issue would be better suited in the memflow-reclass-plugin project.

The problem you're facing is basically caused by pcileech itself having a quite high latency and not that much throughput. The ReClass .NET plugin-system is implemented in such a way that all the requests towards the plugin run on the main thread (which is also the GUI thread). This results in the GUI being quite laggy (especially with the pcileech connector).

I have plans to recode the reclass plugin in such a way that it uses a reactive approach by sending the requests into channels and consuming them on another thread. This should result in the GUI not being dependent on the read speed anymore.
